# Generated by Django 6.0.3 on 2026-03-05 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField(default=1)),
                ('leg', models.PositiveSmallIntegerField(default=1)),
                ('group_label', models.CharField(blank=True, help_text='e.g. A, B, C', max_length=5)),
                ('stage', models.CharField(choices=[('league', 'League'), ('group', 'Group Stage'), ('r32', 'Round of 32'), ('r16', 'Round of 16'), ('qf', 'Quarter-Final'), ('sf', 'Semi-Final'), ('final', 'Final')], default='league', max_length=10)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to=settings.AUTH_USER_MODEL)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='competitions.competition')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['round_number', 'leg', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.PositiveSmallIntegerField()),
                ('away_score', models.PositiveSmallIntegerField()),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fixture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='fixtures.fixture')),
            ],
        ),
    ]
