# Generated by Django 6.0.3 on 2026-03-05 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('format', models.CharField(choices=[('league', 'League'), ('knockout', 'Knockout Cup'), ('group_knockout', 'Group Stage + Knockout'), ('round_robin', 'Round Robin')], default='league', max_length=20)),
                ('group_count', models.PositiveSmallIntegerField(default=2)),
                ('legs_per_fixture', models.PositiveSmallIntegerField(default=1)),
                ('transfer_window_seconds', models.PositiveIntegerField(default=120, help_text='Seconds per auction lot (the transfer window timer)')),
                ('starting_budget', models.BigIntegerField(default=100000000)),
                ('squad_size', models.PositiveSmallIntegerField(default=18)),
                ('min_bid_increment', models.BigIntegerField(default=500000)),
                ('unsold_rule', models.CharField(choices=[('requeue', 'Re-queue'), ('highest', 'Goes to highest'), ('skip', 'Skip')], default='highest', max_length=20)),
                ('min_player_rating', models.PositiveSmallIntegerField(default=75)),
                ('max_player_rating', models.PositiveSmallIntegerField(default=99)),
                ('invite_code', models.CharField(blank=True, max_length=12, unique=True)),
                ('status', models.CharField(choices=[('setup', 'Setup'), ('auction', 'Auction'), ('playing', 'Playing'), ('completed', 'Completed')], default='setup', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allowed_clubs', models.ManyToManyField(blank=True, related_name='competitions', to='players.club')),
                ('allowed_leagues', models.ManyToManyField(blank=True, related_name='competitions', to='players.league')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_competitions', to=settings.AUTH_USER_MODEL)),
                ('nominated_players', models.ManyToManyField(blank=True, related_name='nominated_in', to='players.eafcplayer')),
                ('participants', models.ManyToManyField(blank=True, related_name='competitions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_budget', models.BigIntegerField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='competitions.competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('competition', 'user')},
            },
        ),
    ]
