# Generated by Django 6.0.3 on 2026-03-05 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        ('players', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('formation', models.CharField(default='4-3-3', max_length=20)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squads', to='competitions.competition')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SquadSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.PositiveSmallIntegerField()),
                ('is_starter', models.BooleanField(default=True)),
                ('price_paid', models.BigIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.eafcplayer')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squads.squad')),
            ],
            options={
                'ordering': ['slot_number'],
                'unique_together': {('squad', 'slot_number')},
            },
        ),
        migrations.AddField(
            model_name='squad',
            name='players',
            field=models.ManyToManyField(blank=True, through='squads.SquadSlot', to='players.eafcplayer'),
        ),
        migrations.AlterUniqueTogether(
            name='squad',
            unique_together={('competition', 'manager')},
        ),
    ]
