# Generated by Django 6.0.3 on 2026-03-05 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ea_id', models.IntegerField(default=0, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ea_id', models.IntegerField(default=0, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('logo_url', models.URLField(blank=True)),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.league')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EAFCPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ea_id', models.IntegerField(unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('overall', models.PositiveSmallIntegerField(db_index=True)),
                ('position', models.CharField(choices=[('GK', 'GK'), ('CB', 'CB'), ('LB', 'LB'), ('RB', 'RB'), ('LWB', 'LWB'), ('RWB', 'RWB'), ('CDM', 'CDM'), ('CM', 'CM'), ('CAM', 'CAM'), ('LM', 'LM'), ('RM', 'RM'), ('LW', 'LW'), ('RW', 'RW'), ('CF', 'CF'), ('ST', 'ST')], db_index=True, max_length=5)),
                ('alt_positions', models.CharField(blank=True, help_text='Comma-separated alt positions', max_length=30)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('nationality_id', models.IntegerField(blank=True, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight_kg', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True)),
                ('pace', models.PositiveSmallIntegerField(default=0)),
                ('shooting', models.PositiveSmallIntegerField(default=0)),
                ('passing', models.PositiveSmallIntegerField(default=0)),
                ('dribbling', models.PositiveSmallIntegerField(default=0)),
                ('defending', models.PositiveSmallIntegerField(default=0)),
                ('physicality', models.PositiveSmallIntegerField(default=0)),
                ('gk_diving', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gk_handling', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gk_kicking', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gk_reflexes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gk_speed', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gk_positioning', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('acceleration', models.PositiveSmallIntegerField(default=0)),
                ('sprint_speed', models.PositiveSmallIntegerField(default=0)),
                ('positioning', models.PositiveSmallIntegerField(default=0)),
                ('finishing', models.PositiveSmallIntegerField(default=0)),
                ('shot_power', models.PositiveSmallIntegerField(default=0)),
                ('long_shots', models.PositiveSmallIntegerField(default=0)),
                ('volleys', models.PositiveSmallIntegerField(default=0)),
                ('penalties', models.PositiveSmallIntegerField(default=0)),
                ('vision', models.PositiveSmallIntegerField(default=0)),
                ('crossing', models.PositiveSmallIntegerField(default=0)),
                ('fk_accuracy', models.PositiveSmallIntegerField(default=0)),
                ('short_passing', models.PositiveSmallIntegerField(default=0)),
                ('long_passing', models.PositiveSmallIntegerField(default=0)),
                ('curve', models.PositiveSmallIntegerField(default=0)),
                ('agility', models.PositiveSmallIntegerField(default=0)),
                ('balance', models.PositiveSmallIntegerField(default=0)),
                ('reactions', models.PositiveSmallIntegerField(default=0)),
                ('ball_control', models.PositiveSmallIntegerField(default=0)),
                ('dribbling_sub', models.PositiveSmallIntegerField(default=0)),
                ('composure', models.PositiveSmallIntegerField(default=0)),
                ('interceptions', models.PositiveSmallIntegerField(default=0)),
                ('heading_accuracy', models.PositiveSmallIntegerField(default=0)),
                ('def_awareness', models.PositiveSmallIntegerField(default=0)),
                ('standing_tackle', models.PositiveSmallIntegerField(default=0)),
                ('sliding_tackle', models.PositiveSmallIntegerField(default=0)),
                ('jumping', models.PositiveSmallIntegerField(default=0)),
                ('stamina', models.PositiveSmallIntegerField(default=0)),
                ('strength', models.PositiveSmallIntegerField(default=0)),
                ('aggression', models.PositiveSmallIntegerField(default=0)),
                ('skill_moves', models.PositiveSmallIntegerField(default=2)),
                ('weak_foot', models.PositiveSmallIntegerField(default=2)),
                ('preferred_foot', models.CharField(blank=True, max_length=10)),
                ('work_rate', models.CharField(blank=True, max_length=20)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.club')),
            ],
            options={
                'ordering': ['-overall', 'name'],
                'indexes': [models.Index(fields=['overall', 'position'], name='players_eaf_overall_9fbdfa_idx'), models.Index(fields=['club'], name='players_eaf_club_id_3f51f7_idx'), models.Index(fields=['name'], name='players_eaf_name_d2c0db_idx')],
            },
        ),
    ]
