# Generated by Django 6.0.3 on 2026-03-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eafcplayer',
            name='alt_positions',
            field=models.CharField(blank=True, help_text='Comma-separated alt positions', max_length=100),
        ),
        migrations.AlterField(
            model_name='eafcplayer',
            name='position',
            field=models.CharField(choices=[('GK', 'GK'), ('CB', 'CB'), ('LB', 'LB'), ('RB', 'RB'), ('LWB', 'LWB'), ('RWB', 'RWB'), ('CDM', 'CDM'), ('CM', 'CM'), ('CAM', 'CAM'), ('LM', 'LM'), ('RM', 'RM'), ('LW', 'LW'), ('RW', 'RW'), ('CF', 'CF'), ('ST', 'ST')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='eafcplayer',
            name='preferred_foot',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='eafcplayer',
            name='work_rate',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]