# Generated by Django 6.0.3 on 2026-03-08 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        ('players', '0002_alter_eafcplayer_alt_positions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
                ('label', models.CharField(blank=True, help_text='Optional label e.g. "Day 1 — Stars"', max_length=60)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='AuctionLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('starting_price', models.BigIntegerField(default=1000000)),
                ('current_price', models.BigIntegerField(default=1000000)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('is_settled', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('sold', 'Sold'), ('unsold', 'Unsold')], default='pending', max_length=10)),
                ('sold_price', models.BigIntegerField(blank=True, null=True)),
                ('relisted', models.BooleanField(default=False, help_text='Was this a relist from a previous unsold lot?')),
                ('current_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_lots', to=settings.AUTH_USER_MODEL)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='auction.auctionday')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auction_lots', to='players.eafcplayer')),
                ('sold_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_lots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AuctionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('competition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auction_session', to='competitions.competition')),
            ],
        ),
        migrations.AddField(
            model_name='auctionday',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='auction.auctionsession'),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auction.auctionlot')),
            ],
            options={
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_offered', models.BigIntegerField(default=0)),
                ('cash_wanted', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_offers', to='competitions.competition')),
                ('from_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_offers', to=settings.AUTH_USER_MODEL)),
                ('players_offered', models.ManyToManyField(blank=True, related_name='offered_in_trades', to='players.eafcplayer')),
                ('players_wanted', models.ManyToManyField(blank=True, related_name='wanted_in_trades', to='players.eafcplayer')),
                ('to_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='auctionday',
            unique_together={('session', 'date')},
        ),
    ]
